######################## default configuration ####################
baseURL = "https://keratoconusguide.netlify.app/"
languageCode = "en-us"
title = "Keratoconus Blog"
theme = "liva-hugo"
summaryLength = "10"
paginate = 8
disqusShortname = "keratoconusguide"

[outputs]
  home = ["HTML", "RSS", "JSON"]

############################# Plugins ##############################
[params.plugins]

  # CSS Plugins
  [[params.plugins.css]]
  URL = "plugins/bootstrap/bootstrap.min.css"
  [[params.plugins.css]]
  URL = "plugins/slick/slick.css"
  [[params.plugins.css]]
  URL = "plugins/themify-icons/themify-icons.css"
  [[params.plugins.css]]
  URL = "plugins/venobox/venobox.css"

  # JS Plugins
  [[params.plugins.js]]
  URL = "plugins/jQuery/jquery.min.js"
  [[params.plugins.js]]
  URL = "plugins/bootstrap/bootstrap.min.js"
  [[params.plugins.js]]
  URL = "plugins/slick/slick.min.js"
  [[params.plugins.js]]
  URL = "plugins/venobox/venobox.min.js"
  [[params.plugins.js]]
  URL = "plugins/search/fuse.min.js"
  [[params.plugins.js]]
  URL = "plugins/search/mark.js"
  [[params.plugins.js]]
  URL = "plugins/search/search.js"


############################## navigation ###############################
[menu]

  # main menu
  [[menu.main]]
  name = "About"
  URL = "about"
  weight = 1

  [[menu.main]]
  name = "Blog"
  URL = "blog"
  weight = 2

  [[menu.main]]
  name = "Contact"
  URL = "contact"
  weight = 3

  [[menu.main]]
  name = "Assets"
  URL = "assets"
  weight = 4

  # footer menu
  [[menu.footer]]
  name = "About"
  URL = "about"
  weight = 1

  [[menu.footer]]
  name = "Post"
  URL = "blog"
  weight = 2

  [[menu.footer]]
  name = "Privacy Policy"
  URL = "privacy"
  weight = 3
  


#################### default parameters ################################
[params]
# logo = "images/logo2.png"
home = "Home"
# Meta data
description = "Keratoconus health site"
author = "Heriberto Rangel"
# Google Analitycs
googleAnalitycsID = "UA-96831082-1"
# Contact Information
email = "hrangelm@gmail.com"
location = "mexico city"
# copyright
copyright = "| copyright &copy; 2024 [KUG](https://themefisher.com/hugo-themes/) All Rights Reserved |"

  # Preloader
  [params.preloader]
  enable = true
  preloader = "" # use .png , .svg or .gif format

  # search
  [params.search]
  enable = true

############################ news letter ########################
[params.newsletter]
enable = false
title = "Join the newsletter"
content = "We can improve our life by bringing attention to what we do; get the latest information and news about Keratoconus."

# cookies
[params.cookies]
enable = true
expire_days = 2


############################# social site ########################
[[params.social]]
title = "facebook"
icon = "ti-facebook" # themify icon : https://themify.me/themify-icons
link = "https://facebook.com/heribertorm/"

[[params.social]]
title = "twitter"
icon = "ti-twitter-alt" # themify icon : https://themify.me/themify-icons
link = "https://twitter.com/hrangelma/"

[[params.social]]
title = "reddit"
icon = "ti-reddit" # themify icon : https://themify.me/themify-icons
link = "https://www.reddit.com/r/Keratoconus/"

############################# site map ############################

[sitemap]
  changefreq = 'monthly'
  filename = 'sitemap.xml'
  priority = 0.5

